server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
 
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: cos
    password: cos1234
    url: jdbc:mariadb://localhost:3306/cosdb?serverTimezone=Asia/Seoul
    
  jpa:
    hibernate:
      ddl-auto: none  # create, none
    show-sql: true     # true: console에 'Hibernate: insert into user (email, password, username) values (?, ?, ?)' 보여줌